language: node_js
dist: trusty
branches:
  only:
    - master
cache:
  yarn: true
  directories:
    - node_modules
node_js:
  - '8'
jobs:
  include:
    - stage: test
      script:
        - node --version
        - yarn --version
        - yarn test
notifications:
  email:
    on_failure: change
